In [1]:
import numpy as np
n=np.array([10,20,30,40])


array([10, 20, 30, 40])

In [2]:
nn=np.array([[20,30,40,40],[22,33,44,55]])
nn

array([[20, 30, 40, 40],
       [22, 33, 44, 55]])

In [4]:
n1=np.array([10,15,20,30])
np.intersect1d(n,n1)

array([10, 20, 30])

In [6]:
type(n1)

numpy.ndarray

In [8]:
nn=np.zeros((1,3))

In [9]:
nn

array([[0., 0., 0.]])

In [11]:
nn=np.zeros((2,4))
nn

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
nn=np.zeros((5,5))
nn

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
n1=np.full((2,2),10)
n1

array([[10, 10],
       [10, 10]])

In [18]:
n1=np.full((2,4),12)
n1

array([[12, 12, 12, 12],
       [12, 12, 12, 12]])

In [21]:
na=np.arange(1,10)
na

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
na=np.arange(50,100,5)
na

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [26]:
n1=np.random.randint (1,100,5)
n1

array([18, 32, 32, 52, 99])

In [30]:
n1=np.random.randint(1,10,5)
n1

array([9, 1, 9, 7, 9])

In [32]:
a1=np.array([[1,2,3,4],[4,5,6,7]])
a1.shape

(2, 4)

In [39]:
a1.shape=(2,4)
a1.shape

(2, 4)

In [40]:
a1

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [42]:
a1.shape=(1,8)
a1

array([[1, 2, 3, 4, 4, 5, 6, 7]])

In [45]:
a1.shape=(8,1)
a1

array([[1],
       [2],
       [3],
       [4],
       [4],
       [5],
       [6],
       [7]])

In [55]:
a1=np.array([1,2,3,4,5])
a2=np.array([11,12,13,14,15])
np.vstack((a1,a2))

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [56]:
a1=np.array([1,2,3,4,5,6])
a2=np.array([11,12,13,14,15,16])
np.hstack((a1,a2))

array([ 1,  2,  3,  4,  5,  6, 11, 12, 13, 14, 15, 16])

In [60]:
np.column_stack((a1,a2))

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16]])

In [63]:
a=np.array([1,2,3,4])
b=np.array([1,4,5,0])
np.intersect1d(a,b)

array([1, 4])

In [65]:
np.setdiff1d(a,b)

array([2, 3])

In [66]:
np.setdiff1d(b,a)

array([0, 5])

In [68]:
np.sum([a,b])

20

In [70]:
np.sum([a,b],axis=0)

array([2, 6, 8, 4])

In [71]:
np.sum([a,b],axis=1)

array([10, 10])

In [73]:
a=a+1
a

array([3, 4, 5, 6])

In [75]:
a=a-1
a

array([1, 2, 3, 4])

In [77]:
a=a/1
a

array([1., 2., 3., 4.])

In [79]:
a=a*2
a

array([ 4.,  8., 12., 16.])

In [81]:
a=np.array([1,2,3,4,5])
np.mean (a)

3.0

In [83]:
a=np.array([1,2,4,5])
np.median(a)

3.0